// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wghmuvgdlfqagzgcbtae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnaG11dmdkbGZxYWd6Z2NidGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTg3NTQsImV4cCI6MjA2NTQzNDc1NH0.WXcR5DcOvqMvZYIH6JK2ABJa1cMfSv8H60ROZGSSfp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);